version: '3.8'

services:
  app:
    build: .
    container_name: runwaystyle_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo
    container_name: runwaystyle_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
